services:
  workspace:
    build: .
    container_name: BigData_workspace
    ports:
      - "8888:8888"   # Jupyter Lab
      - "6080:6080"   # Visualizador del Scraper (VNC)
      - "4040:4040"   # Spark UI
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    dns:
      - 8.8.8.8
    user: root
    restart: always
    networks:
      - bigdata_net

  visualizer:
    image: mongo-express
    container_name: BigData_Visualizer
    ports:
      - "8081:8081"   # Mongo Express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb+srv://FelipeGutierrez:pepe1516@cluster0.6zjv54l.mongodb.net/?appName=Cluster0
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - VC_NODE_TLS_REJECT_UNAUTHORIZED=0
    dns:
      - 8.8.8.8
    restart: always
    networks:
      - bigdata_net

  filebrowser:
    image: filebrowser/filebrowser
    container_name: BigData_FileBrowser
    ports:
      - "8082:80"     # Gestor de archivos
    volumes:
      - .:/srv
    restart: always
    networks:
      - bigdata_net

networks:
  bigdata_net:
    driver: bridge
    name: BigData_Network_UCN